services:
  next-app:
    container_name: webapp-auth-v3-prod
    build:
      context: ./next-app
      dockerfile: /docker/prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
        TEST_VARIABLE: ${TEST_VARIABLE}
        DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public
    restart: always
    ports:
      - 3001:3000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    container_name: postgres-auth-v3
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
